import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/app/Components/Nav";
import Footer from "@/app/Components/Footer";
import { ThemeProvider } from "@/app/Components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jitendra Biswas - Full Stack Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col px-[30vw] lg:px-[25vw] max-lg:px-[20vw] max-md:px-[5vw] dark:bg-black">
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        disableTransitionOnChange
        >
          <Nav />
        {children}
        <Footer />
        </ThemeProvider>
        
        </body>
    </html>
  );
}
